---
- hosts: nodes
  tasks:
    - name: Fix the /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: "search cluster.local.*"
        line: "search cluster.local"
        state: present

    - name: Remove file /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
      command: rm -f /etc/NetworkManager/dispatcher.d/99-origin-dns.sh


    - name: Set the PEERDNS of enps03 to no
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: "PEERDNS=\"no\""
        line: "PEERDNS=\"no\""
        state: present

    - name: Restart origin-node
      command: systemctl restart origin-node


