---
- hosts: nodes
  tasks:
    - name: Set the hostname
      command: "hostnamectl set-hostname {{ inventory_hostname }}"
      
    - name: Download dependencies
      yum: 
        name: '{{ packages }}'
      vars:
        packages: 
          - wget
          - git
          - net-tools
          - bind-utils
          - yum-utils
          - iptables-services
          - bridge-utils
          - bash-completion
          - kexec-tools
          - sos
          - psacct
          - python-passlib

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    
    - name: reboot
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

    - name: Install Docker
      yum:
        name: docker-1.13.1
        state: present

    - name: Enable docker
      shell: "systemctl enable docker && systemctl start docker"

    - name: debug
      debug:
        var: ansible_host

